# Generated by Django 4.1.4 on 2022-12-23 18:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField()),
                ("email", models.EmailField(max_length=254)),
                ("dob", models.DateField()),
                ("symptoms", models.TextField()),
                ("diagnosis", models.TextField()),
                ("completed", models.BooleanField(default=False)),
            ],
        ),
    ]
