# Generated by Django 4.1.4 on 2022-12-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_remove_chat_completed"),
    ]

    operations = [
        migrations.RenameField(model_name="chat", old_name="id", new_name="unique_id",),
        migrations.AlterField(
            model_name="chat", name="name", field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name="chat", name="symptoms", field=models.CharField(max_length=1000),
        ),
    ]
