# Generated by Django 4.1.4 on 2022-12-23 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_chat_id_alter_chat_unique_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chat", old_name="unique_id", new_name="patient_id",
        ),
    ]
