# Generated by Django 4.1.4 on 2022-12-24 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_rename_unique_id_chat_patient_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chat", old_name="name", new_name="patient_name",
        ),
        migrations.AlterField(
            model_name="chat", name="diagnosis", field=models.TextField(editable=False),
        ),
    ]
